services:
    mysql-db:
        image: mysql:latest
        restart: unless-stopped
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
            - MYSQL_DATABASE=${DB_NAME}
        ports:
            - "3306:3306"
        volumes:
            - db:/var/lib/mysql
    app:
        build:
            dockerfile: Dockerfile
            context: .
        volumes:
            - ./:/home/node/app/
        env_file:
            - .env
        ports:
            - 3000:3000
        depends_on:
            - mysql-db
volumes:
    db: